spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mynew?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: admin
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp